# Generated by Django 4.1.7 on 2023-03-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuario",
            new_name="User",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="nome",
            new_name="name",
        ),
    ]
