# Generated by Django 4.1.7 on 2023-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_backend", "0002_rename_usuario_user_rename_nome_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
