on:
  # allows to manually run the job at any time
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/badges-action-markdown.yml'

permissions: read-all|write-all
jobs:
  update-profile-badges:
    runs-on: ubuntu-latest
    name: Update profile badges
    steps:
      - name: Update Badges
        uses: kamuridesu/markdown-badges@v0.0.2
        with:
          BADGES: "Python Django RabbitMQ Nginx"
